import ExcelJS from 'exceljs';
import { existsSync } from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit';
import { generateBalanceSheet } from './balanceSheet.js';

function currency(value) {
  return `$${Number(value || 0).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function ensureBalanceSheet(transactions, balanceSheet) {
  return balanceSheet || generateBalanceSheet(transactions);
}

function checkPageSpace(doc, neededHeight) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (doc.y + neededHeight > bottom) {
    doc.addPage();
  }
}

function drawCell(doc, text, x, y, width, height, options = {}) {
  doc
    .lineWidth(0.5)
    .strokeColor('#d8d8de')
    .rect(x, y, width, height)
    .stroke();

  doc
    .font(options.bold ? 'Helvetica-Bold' : 'Helvetica')
    .fontSize(options.fontSize || 8.5)
    .fillColor(options.color || '#111111')
    .text(String(text ?? ''), x + 7, y + 7, {
      width: width - 14,
      height: height - 10,
      align: options.align || 'left',
      ellipsis: true,
    });
}

function drawTable(doc, title, columns, rows, options = {}) {
  const x = doc.page.margins.left;
  const tableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const headerHeight = options.headerHeight || 24;
  const rowHeight = options.rowHeight || 27;
  const titleHeight = 25;
  const columnWidths = columns.map((column) => column.width);
  const widthSum = columnWidths.reduce((total, width) => total + width, 0);
  const scaledWidths = columnWidths.map((width) => (width / widthSum) * tableWidth);

  checkPageSpace(doc, titleHeight + headerHeight + rowHeight);
  doc.moveDown(0.8);
  doc.font('Helvetica-Bold').fontSize(11).fillColor('#050505').text(title.toUpperCase(), x, doc.y);
  doc.moveDown(0.35);

  let y = doc.y;
  let currentX = x;

  columns.forEach((column, index) => {
    drawCell(doc, column.label, currentX, y, scaledWidths[index], headerHeight, {
      bold: true,
      fontSize: 8,
      color: '#050505',
      align: column.align,
    });
    currentX += scaledWidths[index];
  });
  y += headerHeight;

  rows.forEach((row) => {
    checkPageSpace(doc, rowHeight);
    y = doc.y;
    currentX = x;

    columns.forEach((column, index) => {
      drawCell(doc, row[column.key], currentX, y, scaledWidths[index], rowHeight, {
        fontSize: options.fontSize || 8.3,
        align: column.align,
      });
      currentX += scaledWidths[index];
    });

    doc.y = y + rowHeight;
  });

  doc.moveDown(0.4);
}

function drawReportHeader(doc, transactions, sheet) {
  const left = doc.page.margins.left;
  const logoPath = path.resolve(process.cwd(), '..', 'logo.png');

  if (existsSync(logoPath)) {
    doc.image(logoPath, left, 40, { width: 86 });
  } else {
    doc.font('Helvetica-Bold').fontSize(18).fillColor('#050505').text('Ledgerix', left, 44);
  }

  doc.font('Helvetica').fontSize(8.5).fillColor('#6f6f76').text('Generated by Smart Balance Sheet Generator', left, 82);

  doc
    .font('Helvetica-Bold')
    .fontSize(22)
    .fillColor('#050505')
    .text('Balance Sheet Report', left, 116);

  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor('#6f6f76')
    .text(`Company: Ledgerix`, left, 146)
    .text(`Generated: ${new Date().toLocaleString()}`)
    .text(`Rows processed: ${transactions.length}`);

  const status = sheet.equation.isBalanced ? 'Balanced' : 'Needs Review';
  const statusColor = sheet.equation.isBalanced ? '#111111' : '#bd332b';
  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .fillColor(statusColor)
    .text(`Statement status: ${status}`, 380, 146, { align: 'right' })
    .font('Helvetica')
    .fontSize(9)
    .fillColor('#6f6f76')
    .text(`Difference: ${currency(sheet.equation.difference)}`, 380, 162, { align: 'right' });

  doc.y = 196;
  doc.moveTo(left, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).strokeColor('#d8d8de').stroke();
}

function statementRows(sheet) {
  return ['assets', 'liabilities', 'equity', 'revenue', 'expenses'].flatMap((section) => {
    const rows = sheet[section] || [];
    if (!rows.length) {
      return [[section.toUpperCase(), 'No classified accounts', currency(0)]];
    }
    return rows.map((item) => [section.toUpperCase(), item.account, currency(item.balance)]);
  });
}

export function createPdfReport(transactions, balanceSheet) {
  const sheet = ensureBalanceSheet(transactions, balanceSheet);
  const doc = new PDFDocument({ margin: 48, size: 'A4' });
  const chunks = [];

  doc.on('data', (chunk) => chunks.push(chunk));

  drawReportHeader(doc, transactions, sheet);

  drawTable(
    doc,
    'Balance Sheet Summary',
    [
      { key: 'metric', label: 'Metric', width: 3 },
      { key: 'amount', label: 'Amount', width: 2, align: 'right' },
    ],
    [
      { metric: 'Assets', amount: currency(sheet.totals.assets) },
      { metric: 'Liabilities', amount: currency(sheet.totals.liabilities) },
      { metric: 'Equity', amount: currency(sheet.totals.equity) },
      { metric: 'Revenue', amount: currency(sheet.totals.revenue) },
      { metric: 'Expenses', amount: currency(sheet.totals.expenses) },
      { metric: 'Net Income', amount: currency(sheet.totals.netIncome) },
      { metric: 'Adjusted Equity', amount: currency(sheet.totals.adjustedEquity) },
      { metric: 'Difference', amount: currency(sheet.equation.difference) },
    ]
  );

  drawTable(
    doc,
    'Account Breakdown',
    [
      { key: 'section', label: 'Section', width: 1.6 },
      { key: 'account', label: 'Account', width: 3.4 },
      { key: 'balance', label: 'Balance', width: 2, align: 'right' },
    ],
    statementRows(sheet).map(([section, account, balance]) => ({ section, account, balance }))
  );

  drawTable(
    doc,
    'Accounting Equation',
    [
      { key: 'assets', label: 'Assets', width: 2 },
      { key: 'funding', label: 'Liabilities + Equity', width: 2.4 },
      { key: 'difference', label: 'Difference', width: 1.8 },
      { key: 'status', label: 'Status', width: 1.5 },
    ],
    [
      {
        assets: currency(sheet.equation.assets),
        funding: currency(sheet.equation.liabilitiesPlusEquity),
        difference: currency(sheet.equation.difference),
        status: sheet.equation.isBalanced ? 'Balanced' : 'Needs review',
      },
    ]
  );

  const transactionRows = transactions.slice(0, 45).map((transaction, index) => ({
    number: index + 1,
    date: transaction.date || '-',
    account: transaction.account,
    category: transaction.category,
    debit: currency(transaction.debit),
    credit: currency(transaction.credit),
    check: transaction.validationStatus,
  }));

  drawTable(
    doc,
    'Transaction Preview',
    [
      { key: 'number', label: '#', width: 0.5 },
      { key: 'date', label: 'Date', width: 1.2 },
      { key: 'account', label: 'Account', width: 2.2 },
      { key: 'category', label: 'Class', width: 1.4 },
      { key: 'debit', label: 'Debit', width: 1.5, align: 'right' },
      { key: 'credit', label: 'Credit', width: 1.5, align: 'right' },
      { key: 'check', label: 'Check', width: 2.1 },
    ],
    transactionRows,
    { rowHeight: 30, fontSize: 7.4 }
  );

  if (transactions.length > 45) {
    doc.moveDown(0.5).font('Helvetica').fontSize(9).fillColor('#6f6f76').text(
      `Showing first 45 of ${transactions.length} transactions. Export Excel for the full transaction list.`
    );
  }

  doc.end();

  return new Promise((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });
}

export async function createExcelReport(transactions, balanceSheet) {
  const sheet = ensureBalanceSheet(transactions, balanceSheet);
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Smart Balance Sheet Generator';

  const summary = workbook.addWorksheet('Balance Sheet');
  summary.columns = [
    { header: 'Section', key: 'section', width: 20 },
    { header: 'Account', key: 'account', width: 30 },
    { header: 'Balance', key: 'balance', width: 16 },
  ];

  ['assets', 'liabilities', 'equity'].forEach((section) => {
    sheet[section].forEach((item) => {
      summary.addRow({ section, account: item.account, balance: item.balance });
    });
  });

  summary.addRow({});
  summary.addRow({ section: 'Totals', account: 'Assets', balance: sheet.totals.assets });
  summary.addRow({ section: 'Totals', account: 'Liabilities + Equity', balance: sheet.equation.liabilitiesPlusEquity });
  summary.addRow({ section: 'Totals', account: 'Difference', balance: sheet.equation.difference });

  const tx = workbook.addWorksheet('Transactions');
  tx.columns = [
    { header: 'Date', key: 'date', width: 14 },
    { header: 'Description', key: 'description', width: 40 },
    { header: 'Account', key: 'account', width: 24 },
    { header: 'Debit', key: 'debit', width: 14 },
    { header: 'Credit', key: 'credit', width: 14 },
    { header: 'Category', key: 'category', width: 16 },
    { header: 'Validation', key: 'validationStatus', width: 28 },
  ];
  transactions.forEach((transaction) => tx.addRow(transaction));

  [summary, tx].forEach((worksheet) => {
    worksheet.getRow(1).font = { bold: true };
    worksheet.columns.forEach((column) => {
      if (['balance', 'debit', 'credit'].includes(column.key)) {
        column.numFmt = '$#,##0.00';
      }
    });
  });

  return workbook.xlsx.writeBuffer();
}
